// app\utils\icons.ts

/**
 * Single source of truth for every icon used in the app. Check here before
 * picking an icon for a new usage — reuse an existing constant if the
 * concept already exists, rather than introducing a second icon for the
 * same idea.
 */
export const ICONS = {
  // Actions
  add: 'i-lucide-plus',
  addCircle: 'i-lucide-circle-plus',
  play: 'i-lucide-play',
  pause: 'i-lucide-pause',
  delete: 'i-lucide-trash',
  edit: 'i-lucide-pencil-line',
  confirm: 'i-lucide-check',
  copy: 'i-lucide-copy',
  share: 'i-lucide-share-2',
  link: 'i-lucide-link',
  close: 'i-lucide-x',
  statusRejected: 'i-lucide-circle-x',
  clear: 'i-lucide-circle-x',
  refresh: 'i-lucide-refresh-cw',
  shuffle: 'i-lucide-shuffle',
  dragHandle: 'i-lucide-grip-vertical',
  undo: 'i-lucide-undo-2',
  search: 'i-lucide-search',
  filter: 'i-lucide-filter',
  filterClear: 'i-lucide-filter-x',
  filterList: 'i-lucide-list-filter',
  filters: 'i-lucide-sliders-horizontal',
  optimize: 'i-lucide-sparkles',
  settings: 'i-lucide-settings',
  settingsColumns: 'i-lucide-settings-2',
  settingsGear: 'i-lucide-settings',
  logout: 'i-lucide-log-out',
  drop: 'i-lucide-log-out',
  lock: 'i-lucide-lock',
  unlock: 'i-lucide-lock-open',
  subtract: 'i-lucide-minus',
  fitView: 'i-lucide-scan',
  draw: 'i-lucide-handshake',
  expand: 'i-lucide-expand',
  collapse: 'i-lucide-minimize',
  booster: 'i-lucide-gift',
  security: 'i-lucide-shield',
  permissions: 'i-lucide-key-round',
  globe: 'i-lucide-globe',
  table: 'i-lucide-table',
  tableView: 'i-lucide-grid-2x2',
  grid: 'i-lucide-layout-grid',
  gridDense: 'i-lucide-grid-3x3',
  chartArea: 'i-lucide-chart-area',
  languages: 'i-lucide-languages',

  // Status / feedback
  success: 'i-lucide-circle-check',
  successFilled: 'i-lucide-circle-check',
  successFilledBig: 'i-lucide-circle-check-big',
  help: 'i-lucide-circle-question-mark',
  helpCircle: 'i-lucide-circle-help',
  loading: 'i-lucide-loader-circle',
  pending: 'i-lucide-circle-dot-dashed',
  banned: 'i-lucide-ban',
  warning: 'i-lucide-triangle-alert',
  alertCircle: 'i-lucide-circle-alert',
  list: 'i-lucide-list',
  listOrdered: 'i-lucide-list-ordered',
  circleDot: 'i-lucide-circle-dot',
  badgeCheck: 'i-lucide-badge-check',
  shieldCheck: 'i-lucide-shield-check',
  tag: 'i-lucide-tag',
  rotateBack: 'i-lucide-rotate-ccw',
  userStar: 'i-lucide-user-star',
  vote: 'i-lucide-star',

  // People
  players: 'i-lucide-users',
  playersRound: 'i-lucide-users-round',
  player: 'i-lucide-user',
  addPlayer: 'i-lucide-user-plus',
  removePlayer: 'i-lucide-user-minus',
  playerConfirmed: 'i-lucide-user-check',
  playerLapsed: 'i-lucide-user-x',
  noShow: 'i-lucide-user-x',
  userRound: 'i-lucide-user-round',

  // Visibility
  show: 'i-lucide-eye',
  hide: 'i-lucide-eye-off',

  // Navigation
  home: 'i-lucide-house',
  chevronDown: 'i-lucide-chevron-down',
  chevronLeft: 'i-lucide-chevron-left',
  chevronRight: 'i-lucide-chevron-right',
  chevronsLeft: 'i-lucide-chevrons-left',
  chevronsRight: 'i-lucide-chevrons-right',
  chevronsUpDown: 'i-lucide-chevrons-up-down',
  forward: 'i-lucide-arrow-right',
  ellipsisVertical: 'i-lucide-ellipsis-vertical',
  bookOpen: 'i-lucide-book-open',
  keyboard: 'i-lucide-keyboard',
  inbox: 'i-lucide-inbox',

  // Sorting
  sortAscNumeric: 'i-lucide-arrow-up-narrow-wide',
  sortDescNumeric: 'i-lucide-arrow-down-wide-narrow',
  sortBoth: 'i-lucide-arrow-up-down',
  sortAlpha: 'i-lucide-arrow-down-a-z',

  // Calendar / time
  calendar: 'i-lucide-calendar',
  calendarAdd: 'i-lucide-calendar-plus',
  calendarRenew: 'i-lucide-calendar-sync',
  calendarCheck: 'i-lucide-calendar-check',
  calendarRange: 'i-lucide-calendar-range',
  clock: 'i-lucide-clock',
  timer: 'i-lucide-timer',
  timerOff: 'i-lucide-timer-off',
  pauseCircle: 'i-lucide-circle-pause',
  history: 'i-lucide-history',
  cake: 'i-lucide-cake',
  trendingUp: 'i-lucide-trending-up',

  // Theme
  lightMode: 'i-lucide-sun',
  darkMode: 'i-lucide-moon',
  themeAuto: 'i-lucide-sun-moon',
  palette: 'i-lucide-palette',

  // Commander / MTG domain
  commander: 'i-lucide-shield-half',
  crown: 'i-lucide-crown',
  terminal: 'i-lucide-terminal',
  shieldUser: 'i-lucide-shield-user',
  shieldPlus: 'i-lucide-shield-plus',
  userRoundCog: 'i-lucide-user-round-cog',
  rules: 'i-lucide-scroll-text',
  battle: 'i-lucide-swords',
  kills: 'i-lucide-sword',
  deaths: 'i-lucide-skull',
  layers: 'i-lucide-layers',
  gameplay: 'i-lucide-gamepad-2',
  cardSearch: 'i-lucide-scan-search',
  manaCost: 'i-lucide-gem',
  deckStats: 'i-lucide-layout-list',
  brewVote: 'i-lucide-flask-round',
  brewVotes: 'i-lucide-flask-conical',
  playVotes: 'i-lucide-zap',
  quickAction: 'i-lucide-zap',

  // League / event / scoring
  standings: 'i-lucide-trophy',
  medal: 'i-lucide-medal',
  chartPie: 'i-lucide-chart-pie',
  chartColumn: 'i-lucide-chart-column-big',
  hash: 'i-lucide-hash',
  total: 'i-lucide-calculator',

  // Payments
  wallet: 'i-lucide-wallet',
  euro: 'i-lucide-euro',
  badgeEuro: 'i-lucide-badge-euro',
  coins: 'i-lucide-coins',
  creditCard: 'i-lucide-credit-card',
  shoppingCart: 'i-lucide-shopping-cart',
  ticket: 'i-lucide-ticket',
  idCard: 'i-lucide-id-card',
  receipt: 'i-lucide-receipt',
  incognito: 'i-lucide-hat-glasses',
  flaskConical: 'i-lucide-flask-conical',

  // Contact / identity fields
  mail: 'i-lucide-mail',
  atSign: 'i-lucide-at-sign',
  phone: 'i-lucide-phone',
  smartphone: 'i-lucide-smartphone',
  mapPin: 'i-lucide-map-pin',
  mapPinPlus: 'i-lucide-map-pin-plus',
  mapPinOff: 'i-lucide-map-pin-off',
  map: 'i-lucide-map',
  heartHandshake: 'i-lucide-heart-handshake',
  flag: 'i-lucide-flag',
  building: 'i-lucide-building',
  mailbox: 'i-lucide-mailbox',
  shop: 'i-lucide-store',

  // Misc UI
  bell: 'i-lucide-bell',
  info: 'i-lucide-info',
  messageCircle: 'i-lucide-message-circle',
  alignLeft: 'i-lucide-align-left',
  image: 'i-lucide-image',
  imageOff: 'i-lucide-image-off',
  externalLink: 'i-lucide-arrow-up-right',
  compareArrows: 'i-lucide-git-compare-arrows',
  megaphone: 'i-lucide-megaphone',
  package: 'i-lucide-package',
  github: 'i-simple-icons-github',

  // Social
  paypal: 'i-simple-icons-paypal',
  facebook: 'i-simple-icons-facebook',
  instagram: 'i-simple-icons-instagram',
  telegram: 'i-simple-icons-telegram',
  whatsapp: 'i-simple-icons-whatsapp',

  // Wanted card print languages (circle-flags set)
  flagEn: 'i-circle-flags-gb',
  flagIt: 'i-circle-flags-it',
  flagEs: 'i-circle-flags-es',
  flagFr: 'i-circle-flags-fr',
  flagDe: 'i-circle-flags-de',
  flagJa: 'i-circle-flags-jp'
} as const

export type IconName = (typeof ICONS)[keyof typeof ICONS]
