// server\utils\telegram\icons.ts
// Single source of truth for every emoji in the Telegram bot, single-use ones included (like
// app/utils/icons.ts for the web app)
export const ICONS = {
  statusDraft: '📋',
  statusRegistrationOpen: '📝',
  statusInProgress: '🔄',
  statusCompleted: '✅',
  statusCancelled: '❌',
  statusExternal: '🏪',
  registrationCheckedIn: '🎯',
  registrationRegistered: '✅',
  registrationNone: '⚪',
  openDetails: 'ℹ️',
  // League headers, classifica headers and prize lines share one trophy glyph
  trophy: '🏆',
  medal: '🏅',
  dice: '🎲',
  date: '🗓️',
  location: '📍',
  calendar: '📅',
  directions: '🧭',
  ticket: '🎟️',
  membershipCard: '🪪',
  fee: '💶',
  // classificheMenu's own format-picker buttons.
  pauper: '👛',
  commander: '👑',
  premodern: '📜',
  cittadino: '🎖️',
  // /prezzo: card header, language filter buttons and foil toggle
  card: '🃏',
  languageAll: '🌐',
  languageIt: '🇮🇹',
  languageEn: '🇬🇧',
  foil: '✨',
  // "Aggiungi alle mie cercate" button
  wanted: '🔍',
  register: '➕',
  // Shared message and button glyphs
  failure: '❌',
  success: '✅',
  warning: '⚠️',
  pending: '⏳',
  thinking: '🤔',
  info: 'ℹ️',
  trash: '🗑',
  shrug: '🤷',
  searchPrint: '🔎',
  back: '↩️',
  wave: '👋🏻',
  link: '🔗',
  help: '📖',
  settings: '⚙️',
  online: '🟢',
  skipNext: '⏭️',
  stadium: '🏟️',
  table: '🪑',
  numbers: '🔢',
  import: '📥',
  coin: '🪙',
  account: '👤',
  unlink: '🔓',
  support: '💬',
  tag: '🏷️',
  refresh: '🔄',
  organizer: '🏢',
  write: '✍️',
  skull: '💀',
  unselected: '⬜',
  next: '➡️',
  selected: '⭐',
  two: '2️⃣',
  playVote: '🎬',
  one: '1️⃣',
  receipt: '🧾',
  edit: '✏️',
  sos: '🆘',
  finishFlag: '🏁',
  commanderCard: '🎴',
  door: '🚪',
  thumbsUp: '👍',
  phone: '☎️',
  stats: '📊',
  versus: '🆚',
  pointDown: '👇🏻',
  stopwatch: '⏱️',
  application: '📋',
  // Prev / next page buttons
  previous: '◀',
  following: '▶'
} as const
