-- Retroactive baseline for the Commander tournament schema (rounds,
-- pairings, round results, standings, kills, votes, rulesets, commander
-- decks) — these tables were created directly against the live database
-- (dashboard/MCP) while planning the Commander flow port from the
-- `league` project, and were never captured in a tracked migration.
-- `20260818130000_updated_at_trigger_everywhere.sql` already references
-- several of them (rulesets/tournament_pairings/tournament_rounds/
-- tournament_standings/commander_decks), confirming they predate that
-- migration and were simply never version-controlled themselves.
--
-- Every statement is written defensively (`if not exists` / `drop ...
-- if exists` before `create`) so this migration is a no-op against the
-- current live database (where everything already exists) while still
-- fully reconstructing the schema from scratch on any fresh environment
-- (local `supabase db reset`, CI, a new Supabase branch). Column types,
-- defaults, constraints, indexes, and RLS policies below were captured
-- by introspecting the live database directly (pg_get_constraintdef,
-- pg_indexes, pg_policies) — this file is a faithful snapshot, not a
-- redesign. Updated_at triggers are NOT recreated here — they're already
-- tracked in 20260818130000_updated_at_trigger_everywhere.sql.

-- === rulesets ============================================================
create table if not exists public.rulesets (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  name text not null,
  version text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_rulesets_uuid_key unique (uuid),
  constraint uq_rulesets_name_key unique (name)
);

alter table public.rulesets enable row level security;

drop policy if exists "public_read" on public.rulesets;
create policy "public_read" on public.rulesets
  for select to public using (true);

drop policy if exists "management_full_access" on public.rulesets;
create policy "management_full_access" on public.rulesets
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === ruleset__descriptions ===============================================
create table if not exists public.ruleset__descriptions (
  id bigint generated by default as identity primary key,
  category text not null,
  description text not null,
  constraint uq_ruleset__descriptions_category_key unique (category)
);

alter table public.ruleset__descriptions enable row level security;

drop policy if exists "public_read" on public.ruleset__descriptions;
create policy "public_read" on public.ruleset__descriptions
  for select to public using (true);

drop policy if exists "management_full_access" on public.ruleset__descriptions;
create policy "management_full_access" on public.ruleset__descriptions
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === ruleset__points ======================================================
create table if not exists public.ruleset__points (
  id bigint generated by default as identity primary key,
  ruleset_uuid uuid not null,
  category text not null,
  points smallint not null,
  constraint fk_rulesets_points_ruleset_uuid
    foreign key (ruleset_uuid) references public.rulesets (uuid)
    on update cascade on delete cascade,
  constraint fk_ruleset__points_category_fkey
    foreign key (category) references public.ruleset__descriptions (category)
    on update cascade on delete restrict
);

create index if not exists idx_rulesets_points_ruleset_uuid
  on public.ruleset__points (ruleset_uuid);
create index if not exists idx_rulesets_points_category
  on public.ruleset__points (category);

alter table public.ruleset__points enable row level security;

drop policy if exists "public_read" on public.ruleset__points;
create policy "public_read" on public.ruleset__points
  for select to public using (true);

drop policy if exists "management_full_access" on public.ruleset__points;
create policy "management_full_access" on public.ruleset__points
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === tournament_rounds ====================================================
create table if not exists public.tournament_rounds (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  tournament_uuid uuid not null,
  round_number smallint not null,
  status text not null default 'scheduled',
  pairings_approved_at timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_tournament_rounds_uuid_key unique (uuid),
  constraint uq_tournament_rounds_unique_round unique (tournament_uuid, round_number),
  constraint fk_tournament_rounds_tournament_uuid_fkey
    foreign key (tournament_uuid) references public.tournaments (uuid) on delete cascade,
  constraint ck_tournament_rounds_status_check
    check (status = any (array['scheduled', 'preview', 'approved', 'in_progress', 'completed']))
);

create index if not exists idx_tournament_rounds_tournament_uuid
  on public.tournament_rounds (tournament_uuid);

alter table public.tournament_rounds enable row level security;

drop policy if exists "public_read" on public.tournament_rounds;
create policy "public_read" on public.tournament_rounds
  for select to public using (true);

drop policy if exists "management_full_access" on public.tournament_rounds;
create policy "management_full_access" on public.tournament_rounds
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === tournament_pairings ===================================================
create table if not exists public.tournament_pairings (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  round_uuid uuid not null,
  tournament_uuid uuid not null,
  table_number smallint,
  player1_uuid uuid,
  player2_uuid uuid,
  player3_uuid uuid,
  player4_uuid uuid,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_tournament_pairings_uuid_key unique (uuid),
  constraint fk_tournament_pairings_round_uuid_fkey
    foreign key (round_uuid) references public.tournament_rounds (uuid) on delete cascade,
  constraint fk_tournament_pairings_tournament_uuid_fkey
    foreign key (tournament_uuid) references public.tournaments (uuid) on delete cascade,
  constraint fk_tournament_pairings_player1_fkey
    foreign key (player1_uuid) references public.players (uuid) on delete restrict,
  constraint fk_tournament_pairings_player2_fkey
    foreign key (player2_uuid) references public.players (uuid) on delete restrict,
  constraint fk_tournament_pairings_player3_fkey
    foreign key (player3_uuid) references public.players (uuid) on delete restrict,
  constraint fk_tournament_pairings_player4_fkey
    foreign key (player4_uuid) references public.players (uuid) on delete restrict,
  constraint ck_tournament_pairings_status_check
    check (status = any (array['pending', 'playing', 'completed'])),
  constraint ck_tournament_pairings_player_count
    check (
      (player1_uuid is not null and player2_uuid is not null and player3_uuid is not null and player4_uuid is null)
      or
      (player1_uuid is not null and player2_uuid is not null and player3_uuid is not null and player4_uuid is not null)
    )
);

create index if not exists idx_tournament_pairings_round_uuid
  on public.tournament_pairings (round_uuid);
create index if not exists idx_tournament_pairings_tournament_uuid
  on public.tournament_pairings (tournament_uuid);
create index if not exists idx_tournament_pairings_player1
  on public.tournament_pairings (player1_uuid);
create index if not exists idx_tournament_pairings_player2
  on public.tournament_pairings (player2_uuid);
create index if not exists idx_tournament_pairings_player3
  on public.tournament_pairings (player3_uuid);
create index if not exists idx_tournament_pairings_player4
  on public.tournament_pairings (player4_uuid);

alter table public.tournament_pairings enable row level security;

drop policy if exists "public_read" on public.tournament_pairings;
create policy "public_read" on public.tournament_pairings
  for select to public using (true);

drop policy if exists "management_full_access" on public.tournament_pairings;
create policy "management_full_access" on public.tournament_pairings
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === commander_decks =======================================================
create table if not exists public.commander_decks (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  player_uuid uuid not null,
  commander_1_name text not null,
  commander_2_name text,
  companion_name text default '',
  decklist_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_commander_decks_uuid unique (uuid),
  constraint fk_commander_decks_player
    foreign key (player_uuid) references public.players (uuid) on delete restrict
);

create index if not exists idx_commander_decks_player_uuid
  on public.commander_decks (player_uuid);
create index if not exists idx_commander_decks_commanders
  on public.commander_decks (commander_1_name, commander_2_name);
create unique index if not exists uq_commander_decks_single
  on public.commander_decks (player_uuid, commander_1_name) where (commander_2_name is null);
create unique index if not exists uq_commander_decks_partner
  on public.commander_decks (player_uuid, commander_1_name, commander_2_name) where (commander_2_name is not null);

alter table public.commander_decks enable row level security;

drop policy if exists "public_read" on public.commander_decks;
create policy "public_read" on public.commander_decks
  for select to public using (true);

drop policy if exists "player_manage_own_decks" on public.commander_decks;
create policy "player_manage_own_decks" on public.commander_decks
  for all to public
  using (player_uuid = (select players.uuid from public.players where players.user_id = auth.uid()))
  with check (player_uuid = (select players.uuid from public.players where players.user_id = auth.uid()));

drop policy if exists "management_full_access" on public.commander_decks;
create policy "management_full_access" on public.commander_decks
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === tournament_round_results ==============================================
create table if not exists public.tournament_round_results (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  pairing_uuid uuid not null,
  tournament_uuid uuid not null,
  player_uuid uuid not null,
  position smallint,
  commander_deck_uuid uuid,
  created_at timestamptz not null default now(),
  constraint uq_tournament_round_results_uuid_key unique (uuid),
  constraint uq_tournament_round_results_unique_player_per_pairing unique (pairing_uuid, player_uuid),
  constraint fk_tournament_round_results_pairing_uuid_fkey
    foreign key (pairing_uuid) references public.tournament_pairings (uuid) on delete cascade,
  constraint fk_tournament_round_results_tournament_uuid_fkey
    foreign key (tournament_uuid) references public.tournaments (uuid) on delete cascade,
  constraint fk_tournament_round_results_player_uuid_fkey
    foreign key (player_uuid) references public.players (uuid) on delete restrict,
  constraint fk_tournament_round_results_commander_deck_uuid_fkey
    foreign key (commander_deck_uuid) references public.commander_decks (uuid) on delete set null,
  constraint ck_tournament_round_results_position_check
    check (position is null or position = any (array[1, 2, 3, 4]))
);

create index if not exists idx_tournament_round_results_pairing_uuid
  on public.tournament_round_results (pairing_uuid);
create index if not exists idx_tournament_round_results_tournament_uuid
  on public.tournament_round_results (tournament_uuid);
create index if not exists idx_tournament_round_results_player_uuid
  on public.tournament_round_results (player_uuid);

alter table public.tournament_round_results enable row level security;

drop policy if exists "public_read" on public.tournament_round_results;
create policy "public_read" on public.tournament_round_results
  for select to public using (true);

drop policy if exists "player_enter_own_result" on public.tournament_round_results;
create policy "player_enter_own_result" on public.tournament_round_results
  for insert to public
  with check (
    player_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
    and exists (
      select 1 from public.tournament_pairings p
      where p.uuid = tournament_round_results.pairing_uuid
        and (
          p.player1_uuid = tournament_round_results.player_uuid
          or p.player2_uuid = tournament_round_results.player_uuid
          or p.player3_uuid = tournament_round_results.player_uuid
          or p.player4_uuid = tournament_round_results.player_uuid
        )
    )
  );

drop policy if exists "management_full_access" on public.tournament_round_results;
create policy "management_full_access" on public.tournament_round_results
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === tournament_standings ===================================================
create table if not exists public.tournament_standings (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  tournament_uuid uuid not null,
  registration_uuid uuid not null,
  player_uuid uuid not null,
  player_score bigint,
  player_rank bigint,
  player_victories bigint,
  votes_brew_received bigint,
  votes_play_received bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_tournament_standings_unique_registration unique (registration_uuid),
  constraint fk_tournament_standings_tournament_uuid_fkey
    foreign key (tournament_uuid) references public.tournaments (uuid) on delete cascade,
  constraint fk_tournament_standings_registration_uuid_fkey
    foreign key (registration_uuid) references public.tournament_registrations (uuid) on delete cascade,
  constraint fk_tournament_standings_player_uuid_fkey
    foreign key (player_uuid) references public.players (uuid) on delete restrict
);

create index if not exists idx_tournament_standings_tournament_uuid
  on public.tournament_standings (tournament_uuid);
create index if not exists idx_tournament_standings_registration_uuid
  on public.tournament_standings (registration_uuid);
create index if not exists idx_tournament_standings_player_uuid
  on public.tournament_standings (player_uuid);

alter table public.tournament_standings enable row level security;

drop policy if exists "public_read" on public.tournament_standings;
create policy "public_read" on public.tournament_standings
  for select to public using (true);

drop policy if exists "management_full_access" on public.tournament_standings;
create policy "management_full_access" on public.tournament_standings
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- === tournament_kills ========================================================
create table if not exists public.tournament_kills (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  pairing_uuid uuid not null,
  tournament_uuid uuid not null,
  killer_uuid uuid not null,
  killed_player_uuid uuid not null,
  created_at timestamptz not null default now(),
  constraint uq_tournament_kills_uuid_key unique (uuid),
  constraint uq_tournament_kills_unique_kill unique (pairing_uuid, killer_uuid, killed_player_uuid),
  constraint fk_tournament_kills_pairing_uuid_fkey
    foreign key (pairing_uuid) references public.tournament_pairings (uuid) on delete cascade,
  constraint fk_tournament_kills_tournament_uuid_fkey
    foreign key (tournament_uuid) references public.tournaments (uuid) on delete cascade,
  constraint fk_tournament_kills_killer_uuid_fkey
    foreign key (killer_uuid) references public.players (uuid) on delete restrict,
  constraint fk_tournament_kills_killed_player_uuid_fkey
    foreign key (killed_player_uuid) references public.players (uuid) on delete restrict,
  constraint ck_tournament_kills_no_self_kill
    check (killer_uuid <> killed_player_uuid)
);

create index if not exists idx_tournament_kills_pairing_uuid
  on public.tournament_kills (pairing_uuid);
create index if not exists idx_tournament_kills_tournament_uuid
  on public.tournament_kills (tournament_uuid);
create index if not exists idx_tournament_kills_killer_uuid
  on public.tournament_kills (killer_uuid);
create index if not exists idx_tournament_kills_killed_player_uuid
  on public.tournament_kills (killed_player_uuid);

alter table public.tournament_kills enable row level security;

drop policy if exists "public_read" on public.tournament_kills;
create policy "public_read" on public.tournament_kills
  for select to public using (true);

drop policy if exists "player_record_kill_in_own_pairing" on public.tournament_kills;
create policy "player_record_kill_in_own_pairing" on public.tournament_kills
  for insert to public
  with check (
    exists (
      select 1 from public.tournament_pairings p
      where p.uuid = tournament_kills.pairing_uuid
        and (
          p.player1_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
          or p.player2_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
          or p.player3_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
          or p.player4_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
        )
    )
  );

drop policy if exists "management_full_access" on public.tournament_kills;
create policy "management_full_access" on public.tournament_kills
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

create or replace view public.tournament_kills_summary as
select pairing_uuid, killer_uuid, count(*) as kill_count
from public.tournament_kills
group by pairing_uuid, killer_uuid;

-- === tournament_votes ========================================================
create table if not exists public.tournament_votes (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  pairing_uuid uuid not null,
  tournament_uuid uuid not null,
  voter_uuid uuid not null,
  voted_player_uuid uuid not null,
  vote_type text not null,
  created_at timestamptz not null default now(),
  constraint uq_tournament_votes_uuid_key unique (uuid),
  constraint uq_tournament_votes_unique_vote unique (pairing_uuid, voter_uuid, voted_player_uuid, vote_type),
  constraint fk_tournament_votes_pairing_uuid_fkey
    foreign key (pairing_uuid) references public.tournament_pairings (uuid) on delete cascade,
  constraint fk_tournament_votes_tournament_uuid_fkey
    foreign key (tournament_uuid) references public.tournaments (uuid) on delete cascade,
  constraint fk_tournament_votes_voter_uuid_fkey
    foreign key (voter_uuid) references public.players (uuid) on delete restrict,
  constraint fk_tournament_votes_voted_player_uuid_fkey
    foreign key (voted_player_uuid) references public.players (uuid) on delete restrict,
  constraint ck_tournament_votes_vote_type_check
    check (vote_type = any (array['brew', 'play'])),
  constraint ck_tournament_votes_no_self_vote
    check (voter_uuid <> voted_player_uuid)
);

create index if not exists idx_tournament_votes_pairing_uuid
  on public.tournament_votes (pairing_uuid);
create index if not exists idx_tournament_votes_tournament_uuid
  on public.tournament_votes (tournament_uuid);
create index if not exists idx_tournament_votes_voter_uuid
  on public.tournament_votes (voter_uuid);
create index if not exists idx_tournament_votes_voted_player_uuid
  on public.tournament_votes (voted_player_uuid);

alter table public.tournament_votes enable row level security;

drop policy if exists "public_read" on public.tournament_votes;
create policy "public_read" on public.tournament_votes
  for select to public using (true);

drop policy if exists "player_vote_in_own_pairing" on public.tournament_votes;
create policy "player_vote_in_own_pairing" on public.tournament_votes
  for insert to public
  with check (
    exists (
      select 1 from public.tournament_pairings p
      where p.uuid = tournament_votes.pairing_uuid
        and (
          p.player1_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
          or p.player2_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
          or p.player3_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
          or p.player4_uuid = (select players.uuid from public.players where players.user_id = auth.uid())
        )
        and (
          tournament_votes.voted_player_uuid = p.player1_uuid
          or tournament_votes.voted_player_uuid = p.player2_uuid
          or tournament_votes.voted_player_uuid = p.player3_uuid
          or tournament_votes.voted_player_uuid = p.player4_uuid
        )
        and tournament_votes.voted_player_uuid <> (select players.uuid from public.players where players.user_id = auth.uid())
    )
  );

drop policy if exists "management_full_access" on public.tournament_votes;
create policy "management_full_access" on public.tournament_votes
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));
