-- Ports league's mtg_commanders catalog table + get_commander_catalog()
-- RPC (user request, 2026-09-16: "dovremmo copiare il catalogo di league e
-- anche la tabella che contiene tutti i comandanti", overriding an earlier
-- session decision to build commander selection against this app's generic
-- Scryfall search instead). Column list and RPC shape are a faithful
-- snapshot of league's final/grown state (reconstructed from
-- league/shared/utils/types/database.ts and the six migrations that grew
-- get_commander_catalog() one field at a time — this migration ports the
-- end state directly rather than replaying each step).
--
-- Read-only reference table: nothing writes to it except the sync job
-- (server/api/admin/sync-commanders.post.ts, management-permission gated)
-- — same public_read/management_full_access split as rulesets/
-- ruleset__points etc. elsewhere in this schema, not a bespoke policy shape.
--
-- A `mtg_commanders` already existed live (confirmed empty, 0 rows) from an
-- earlier out-of-band exploration — same "created before this session's
-- migrations were tracked" situation as the other Commander tables, but
-- with a stale/incomplete column set (missing art_crop_url/large_image_url/
-- back_*/layout/is_double_faced, plus a stray `legalities jsonb` column
-- league's final schema doesn't have) that made `create table if not
-- exists` below silently no-op against the wrong shape, breaking the RPC.
-- Dropped first since there's no data to lose.
drop table if exists public.mtg_commanders cascade;

create table if not exists public.mtg_commanders (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid(),
  scryfall_id text not null,
  card_name text not null,
  image_url text,
  large_image_url text,
  art_crop_url text,
  back_image_url text,
  back_large_image_url text,
  back_art_crop_url text,
  mana_cost text,
  back_mana_cost text,
  cmc numeric,
  color_identity text[],
  type_line text,
  back_type_line text,
  keywords text[],
  oracle_text text,
  back_oracle_text text,
  partner_type text,
  partner_group_tag text,
  partner_with_scryfall_id text,
  edhrec_rank integer,
  layout text,
  is_double_faced boolean,
  scryfall_url text,
  released_at date,
  last_synced_at timestamptz not null default now(),
  constraint uq_mtg_commanders_uuid unique (uuid),
  constraint uq_mtg_commanders_scryfall_id unique (scryfall_id),
  constraint uq_mtg_commanders_card_name unique (card_name),
  constraint fk_mtg_commanders_partner_with
    foreign key (partner_with_scryfall_id) references public.mtg_commanders (scryfall_id)
    on delete set null
);

create index if not exists idx_mtg_commanders_released_at
  on public.mtg_commanders (released_at);

alter table public.mtg_commanders enable row level security;

drop policy if exists "public_read" on public.mtg_commanders;
create policy "public_read" on public.mtg_commanders
  for select to public using (true);

drop policy if exists "management_full_access" on public.mtg_commanders;
create policy "management_full_access" on public.mtg_commanders
  for all to public
  using (has_management_permissions(auth.uid()))
  with check (has_management_permissions(auth.uid()));

-- No updated_at trigger on this table — league's own mtg_commanders has
-- none either; last_synced_at is set explicitly by the sync job's own
-- upsert payload, not a DB trigger.

-- get_commander_catalog(): final/grown field set (card_name, partner_type,
-- keywords, partner_with_scryfall_id, scryfall_id, mana_cost, cmc,
-- color_identity, edhrec_rank, image_url, art_crop_url) — json_agg wraps the
-- whole table in one JSON value so PostgREST's 1000-row-per-request cap
-- never applies (same reasoning already documented in this app's own
-- CLAUDE.md for the unrelated pauperwave_payments/associates case: an
-- unranged .select() silently truncates; here the fix is a single-row RPC
-- instead of fetchAllRows, since the whole catalog is meant to be cached
-- client-side wholesale, not paged).
create or replace function public.get_commander_catalog()
returns json
language sql
stable
as $function$
  select json_agg(row_to_json(t))
  from (
    select card_name, partner_type, keywords, partner_with_scryfall_id,
           scryfall_id, mana_cost, cmc, color_identity, edhrec_rank,
           image_url, art_crop_url
    from public.mtg_commanders
  ) t
$function$;
