// app\types\index.d.ts
import type { AvatarProps } from '@nuxt/ui'
import type { Database } from '#shared/utils/types/database'

export type UserStatus = 'subscribed' | 'unsubscribed' | 'bounced'
export type SaleStatus = 'paid' | 'failed' | 'refunded'

export type RequestStatus = 'approved' | 'pending' | 'rejected'
export type AssociateType = 'ordinario' | 'sostenitore'

// Membership status computed by the pauperwave_associates_with_status view (never
// stored in the DB): 'active'/'to_renew'/'expired' derive from the latest renewal
// year in pauperwave_associate_renewals; for requests not yet approved it matches
// membership_request_status ('pending'/'rejected').
export type MembershipStatus = RequestStatus | 'active' | 'to_renew' | 'expired'

export type TournamentStatus = 'scheduled' | 'canceled' | 'ongoing' | 'completed'

type AssociateRow = Database['public']['Tables']['pauperwave_associates']['Row']

// Derived from shared/utils/types/database.ts (generated by Supabase) so renaming or
// dropping a column is a compile error instead of a silent runtime bug.
export interface Associate extends Omit<AssociateRow, 'membership_request_status' | 'associate_type'> {
  membership_request_status: RequestStatus
  associate_type: AssociateType | null
  membership_status: MembershipStatus
  latest_renewal_year: number | null
  avatar?: AvatarProps
}

export type TransactionStatus = 'paid' | 'failed' | 'refunded'

export interface Transaction {
  id: number
  amount: number
  date: string
  status: TransactionStatus
  associate: Associate
}

export interface Mail {
  id: number
  unread?: boolean
  from: User
  subject: string
  body: string
  date: string
}

export interface Member {
  name: string
  username: string
  role: 'member' | 'owner'
  avatar: AvatarProps
}

export interface Stat {
  title: string
  icon: string
  value: number | string
  variation: number
  formatter?: (value: number) => string
}

export interface Sale {
  id: string
  date: string
  status: SaleStatus
  email: string
  amount: number
}

export interface Notification {
  id: number
  unread?: boolean
  sender: User
  body: string
  date: string
}

export type Period = 'daily' | 'weekly' | 'monthly'

export interface Range {
  start: Date
  end: Date
}

// "searching" = still wanted, "found" = obtained, "abandoned" = the player gave up
// on it (without finding it) — three distinct states, not a boolean: "found" and
// "gave up" have opposite meanings for the statistics.
export type WantedCardStatus = 'searching' | 'found' | 'abandoned'

// snake_case columns of pauperwave_wanted_cards mapped onto this camelCase
// interface in useWantedCards.ts. Shared between wanted-cards/index.vue and its
// components (table, grid, modals) so every view works with the same type.
export interface WantedCard {
  id: number
  date: string
  status: WantedCardStatus
  // Set by a DB trigger when status flips to "found" (null otherwise) — see
  // migrations 20260807230702/20260807231803. Feeds statistics such as "average
  // time to find a card" (date/foundAt), not surfaced in the UI yet.
  foundAt: string | null
  cardName: string
  scryfallUrl: string
  // Null for requests created before migration 20260808120000 — they resolve the
  // direct CardTrader link (server/utils/cardTrader.ts) and have no reliable
  // retroactive default.
  scryfallId: string | null
  setCode: string | null
  copies: number
  language: string
  treatment: string[]
  manaCost: string
  colorIdentity: string[]
  cmc: number
  imageUrl: string
  // Two distinct price sources, not recomputed on every read — snapshots updated
  // by a manual refresh or the weekly job (see server/utils/priceRefresh.ts,
  // scripts/refresh-wanted-cards-prices.mjs). *SyncedAt stays null until a
  // refresh has run on the row.
  cardmarketPrice: number | null
  cardmarketPriceSyncedAt: string | null
  cardtraderPrice: number | null
  cardtraderPriceSyncedAt: string | null
  notes: string
  player: string
  playerAssociateUuid: string
}
