// app\types\index.d.ts
import type { AvatarProps } from '@nuxt/ui'
import type { Database } from '#shared/utils/types/database'
import type { PaymentMethod, PaymentType } from '#shared/types/transactions'
import type { WantedCardLanguage } from '~/utils/wantedCards/wantedCardLanguages'

export type UserStatus = 'subscribed' | 'unsubscribed' | 'bounced'
export type SaleStatus = 'paid' | 'failed' | 'refunded'

// The color a *StatusColor() util (app/utils/status/*.ts) maps a domain
// status onto for its UBadge/UStatusSelect — each util only ever returns a
// subset of this union (e.g. wantedCardStatusColor never returns 'error'),
// so this is the superset every one of them, and every consumer expecting
// one of their return values, can share instead of re-declaring `string`.
export type StatusColor = 'neutral' | 'info' | 'warning' | 'success' | 'error'

export type RequestStatus = 'approved' | 'pending' | 'rejected'
// English DB values, not Italian — translated for display via
// associate.types.* in it.json (see renderAssociateTypeBadge in
// associates/index.vue), same convention as every other status/type enum.
export type AssociateType = 'regular' | 'sustaining'

// Membership status computed by the pauperwave_associates_with_status view (never
// stored in the DB): 'active'/'to_renew'/'expired' derive from the latest renewal
// year in pauperwave_associate_renewals; 'unpaid' is approved but with zero
// renewal rows ever — just submitted /tesseramento, not a lapsed membership,
// distinguished from 'expired' 2026-08-18 (was silently conflated before);
// for requests not yet approved it matches membership_request_status
// ('pending'/'rejected').
export type MembershipStatus = RequestStatus | 'active' | 'to_renew' | 'expired' | 'unpaid'

// Matches the DB check constraint (ck_tournaments_status) verbatim — adopted
// directly instead of mapped to a UI-only vocabulary (2026-08-15 user request).
export type TournamentStatus = 'draft' | 'registration_open' | 'in_progress' | 'completed' | 'cancelled'
// Matches the DB check constraint (ck_leagues_status) verbatim, same
// convention as TournamentStatus/EventStatus (2026-08-15 user request).
export type LeagueStatus = 'draft' | 'active' | 'completed' | 'cancelled'
// Matches the DB check constraint (ck_events_status) verbatim, same
// convention as TournamentStatus (2026-08-15 user request).
export type EventStatus = 'draft' | 'published' | 'ongoing' | 'completed' | 'cancelled'

type AssociateRow = Database['public']['Tables']['pauperwave_associates']['Row']

// Derived from shared/utils/types/database.ts (generated by Supabase) so renaming or
// dropping a column is a compile error instead of a silent runtime bug.
export interface Associate extends Omit<AssociateRow, 'membership_request_status' | 'associate_type'> {
  membership_request_status: RequestStatus
  associate_type: AssociateType | null
  membership_status: MembershipStatus
  latest_renewal_year: number | null
  latest_renewal_date: string | null
  // Whole completed years, computed in pauperwave_associates_with_status
  // (migration 20260818160000) — not derived client-side anymore.
  age: number | null
  avatar?: AvatarProps
}

type PaymentRow = Database['public']['Tables']['pauperwave_payments']['Row']

// Derived from the real pauperwave_payments row (see shared/types/transactions.ts
// for the PaymentMethod/PaymentType value unions, shared with the create
// endpoint/mutation) — `associate` is the joined payer when associate_uuid is
// set, null for an external (non-associate) payer.
export interface Transaction
  extends Omit<PaymentRow, 'payment_type' | 'payment_method' | 'created_by' | 'updated_by'> {
  payment_type: PaymentType
  payment_method: PaymentMethod
  associate: {
    uuid: string
    first_name: string
    last_name: string
    pauperwave_associate_number: string | null
  } | null
  // Resolved names (audit trail, 2026-08-18) — raw created_by/updated_by uuids
  // are joined server-side, same convention as WantedCard.createdBy/updatedBy.
  createdBy: string
  updatedBy: string
  // Joined from tournament_uuid/event_uuid (2026-08-23) so the "Evento" column
  // can link to the tournament/event's own detail page — leagueUuid is what
  // tournamentDetailUrl needs to build the right link (see its own comment).
  tournament: { uuid: string, name: string, leagueUuid: string | null } | null
  event: { uuid: string } | null
}

// players_full joins the players table (user_id) with its associate (name,
// email, pauperwave_associate_number, is_active) — nullable throughout since
// a view row's FK-joined columns are all optional in the generated type,
// even though every one of these is NOT NULL in practice (a player row
// always has an associate_uuid FK).
export type Player = Database['public']['Views']['players_full']['Row']

export interface Mail {
  id: number
  unread?: boolean
  from: User
  subject: string
  body: string
  date: string
}

// The 4-tier app-level role model decided in docs/architecture/roles.md
// (2026-08-10): player < organizer < admin < super_admin — now also the live
// DB enum (shared/utils/types/database.ts's app_role, migration
// 20260817090000).
export type AppRole = 'player' | 'organizer' | 'admin' | 'super_admin'

export interface Stat {
  title: string
  icon: string
  value: number | string
  variation: number
  formatter?: (value: number) => string
  // Tints the icon's leading circle — defaults to primary when omitted (see
  // AssociatesStatsCards.vue). Only 'success'/'error' are used so far, for
  // stats that are inherently good/bad news (new signups vs. lapsed
  // renewals) rather than neutral counts.
  color?: 'primary' | 'success' | 'error'
}

export interface Sale {
  id: string
  date: string
  status: SaleStatus
  email: string
  amount: number
}

export interface Notification {
  id: number
  unread?: boolean
  sender: {
    name: string
    avatar?: AvatarProps
  }
  body: string
  date: string
}

export type Period = 'daily' | 'weekly' | 'monthly'

export interface Range {
  start: Date
  end: Date
}

// "searching" = still wanted, "found" = obtained, "abandoned" = the player gave up
// on it (without finding it) — three distinct states, not a boolean: "found" and
// "gave up" have opposite meanings for the statistics.
export type WantedCardStatus = 'searching' | 'found' | 'abandoned'

// snake_case columns of pauperwave_wanted_cards mapped onto this camelCase
// interface in useWantedCards.ts. Shared between wanted-cards/index.vue and its
// components (table, grid, modals) so every view works with the same type.
export interface WantedCard {
  id: number
  date: string
  status: WantedCardStatus
  // Set by a DB trigger when status flips to "found" (null otherwise) — see
  // migrations 20260807230702/20260807231803. Feeds statistics such as "average
  // time to find a card" (date/foundAt), not surfaced in the UI yet.
  foundAt: string | null
  cardName: string
  scryfallUrl: string
  // Null for requests created before migration 20260808120000 — they resolve the
  // direct CardTrader link (server/utils/cardTrader.ts) and have no reliable
  // retroactive default.
  scryfallId: string | null
  setCode: string | null
  copies: number
  // '' when the requester had no language preference (mapped from a `null`
  // DB row, see useWantedCardsQuery.ts) — WantedCardLanguage itself never
  // includes that case, so a stored row's real language can't be typo'd as
  // the form-only 'any' sentinel (WantedCardLanguageFilter).
  language: WantedCardLanguage | ''
  treatment: string[]
  manaCost: string
  colorIdentity: string[]
  // Scryfall's own field (e.g. "Land", "Creature — Elf Wizard") — null for
  // requests created before migration 20260815090000, backfilled via
  // scripts/backfill-wanted-cards-type-line.mjs. Distinguishes a land from
  // a colorless nonland card, which color_identity alone can't (both are []).
  typeLine: string | null
  cmc: number
  imageUrl: string
  // Two distinct price sources, not recomputed on every read — snapshots updated
  // by a manual refresh or the weekly job (see server/utils/priceRefresh.ts,
  // scripts/refresh-wanted-cards-prices.mjs). *SyncedAt stays null until a
  // refresh has run on the row.
  cardmarketPrice: number | null
  cardmarketPriceSyncedAt: string | null
  cardtraderPrice: number | null
  cardtraderPriceSyncedAt: string | null
  notes: string
  player: string
  playerAssociateUuid: string
  // Audit trail (docs/supabase/2-database.md), names resolved client-side in
  // useWantedCardsQuery.ts — PostgREST can't embed pauperwave_associates'
  // self-referencing FK, but created_by/updated_by here are wanted_cards ->
  // associates (a normal FK), so the join works directly.
  createdAt: string
  updatedAt: string
  createdBy: string
  updatedBy: string
}

// Backed by the real `tournaments` table (migration 20260815100000) — mapped
// from its snake_case rows, with location/organizer/format/event resolved
// from their FK'd tables into flat display strings, onto this camelCase
// interface in useTournamentsQuery.ts, same convention as WantedCard above.
export interface Tournament {
  id: number
  uuid: string
  event: string | null
  // Matched against separately, not by `event` name (2026-08-15) — PublicCalendarPage.vue
  // groups tournaments under their event by uuid, a name collision can't misgroup them.
  eventUuid: string | null
  league: string | null
  // FK uuids alongside their resolved display names above (2026-08-16) —
  // needed to prefill TournamentsListEditModal.vue's selects, which bind by
  // uuid (see useTournamentFormFields.ts), not by the human-readable name.
  leagueUuid: string | null
  formatUuid: string
  organizerUuid: string | null
  locationUuid: string | null
  name: string
  startDate: string
  endDate: string | null
  roundCount: number | null
  registeredPlayers: number | null
  organizer: string | null
  format: string
  status: TournamentStatus
  // Venue name (e.g. "Smart Lab - Centro Giovani Rovereto") — kept separate
  // from `locationAddress` (see locations table, migration 20260815100000)
  // so a maps link can use the precise address while the UI still shows the
  // friendlier name, resolving the old "just the name of the place" TODO.
  location: string | null
  locationAddress: string | null
  // Precise Google Maps place link (locations.google_maps_url) — takes
  // priority over the generic address-search fallback when set, see
  // supabase/migrations/20260816120000_add_locations_google_maps_url.sql.
  locationMapsUrl: string | null
  entryFee: number | null
  description: string | null
  prizes: string | null
  companionCode: string | null
  image: string | null
  // Attribution for `image` when it's a Scryfall art_crop (MagicCardArtPicker.vue,
  // migration 20260820120000) — required alongside the crop per Scryfall's API
  // usage guidelines. Both null whenever `image` is unset or wasn't picked
  // through the card-art picker.
  imageCardName: string | null
  imageCardArtist: string | null
  participants: string[]
  // Distinct from `organizer` (the running club/group, e.g. "Pauperwave") —
  // the specific person to contact about this tournament. Both optional:
  // most tournaments have neither, only a real name implies a phone worth
  // showing (see the Hobbit draft seed, migration 20260815100500).
  contactName: string | null
  contactPhone: string | null
  // Derived by useTournamentsQuery.ts (user request, 2026-08-22, issue #52)
  // — this tournament's 1-based position within its own league, ordered by
  // startDate; null when it has no league. Independent of whether `name`
  // repeats — every tournament in a league gets one. Rendered as a muted
  // superscript suffix by TournamentsStageLabel.vue in styled contexts, or
  // via tournamentStageText() as plain text (tournamentStageLabel.ts)
  // wherever styled markup isn't possible (select options, breadcrumbs).
  stageNumber: number | null
}

// Backed by the real `leagues` table — mapped from its snake_case rows, with
// ruleset resolved from its FK'd table, same convention as Tournament above.
// tournamentCount/completedTournamentCount are derived (count of
// tournaments.league_uuid = this league, and of those with status
// 'completed'), not stored columns.
export interface League {
  id: number
  uuid: string
  status: LeagueStatus
  name: string
  startDate: string
  ruleset: string | null
  // FK uuid alongside its resolved display name above (2026-08-16) — needed
  // to prefill LeaguesListEditModal.vue's ruleset select, which binds by
  // uuid, not by the human-readable name — same convention as Tournament's
  // formatUuid/leagueUuid/etc.
  rulesetUuid: string | null
  image: string | null
  // Same attribution pair as Tournament.imageCardName/imageCardArtist above —
  // cascades onto every linked tournament's own pair alongside `image` (see
  // server/api/leagues/[id]/update.post.ts).
  imageCardName: string | null
  imageCardArtist: string | null
  tournamentCount: number
  completedTournamentCount: number
  // Derived from the same lightweight tournaments read as
  // tournamentCount/completedTournamentCount above (ADR, docs/PROGRESS.md,
  // 2026-08-22) — distinct format names among this league's tournaments
  // (any status; a cancelled tournament's format is still informative),
  // sorted alphabetically. Empty when the league has none yet.
  tournamentFormats: string[]
  // Earliest/latest tournament starts_at in this league — null when it has
  // no tournaments yet (falls back to `startDate` above for display in that
  // case). Same "tournaments are the source of truth for a league's real
  // date span" reasoning already used ad hoc by leagues/[leagueId]/index.vue
  // and locations/[slug]/index.vue's own heatmaps, now available wherever a
  // League is read instead of recomputed per page.
  tournamentDateRange: { start: string, end: string } | null
}

// Backed by the real `events` table — mapped from its snake_case rows, with
// location/organizer resolved from their FK'd tables into flat display
// strings, same convention as Tournament above. tournamentCount is derived
// (count of tournaments.event_uuid = this event), not a stored column.
export interface Event {
  id: number
  uuid: string
  status: EventStatus
  name: string
  startDate: string
  endDate: string | null
  tournamentCount: number
  organizer: string | null
  // FK uuids alongside their resolved display names above (2026-08-22,
  // EventsListEditModal.vue) — needed to prefill the edit form's
  // organizer/location selects, which bind by uuid, not by the
  // human-readable name — same convention as Tournament's own
  // organizerUuid/locationUuid.
  organizerUuid: string
  locationUuid: string | null
  location: string | null
  locationAddress: string | null
  // Precise Google Maps place link (locations.google_maps_url), see
  // Tournament's own locationMapsUrl for why this takes priority over the
  // generic address-search fallback — added 2026-08-22 alongside
  // Card.vue/Cover.vue (issue #45).
  locationMapsUrl: string | null
  image: string | null
  companionCode: string | null
}

export type DayOfWeek
  = | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'

// null = closed that day; HH:mm strings otherwise. Always has all 7 keys
// (OpeningHoursEditor.vue initializes every day, closed or not) rather than
// only the open ones, so the editor never has to guess a day is unset vs.
// deliberately closed.
export type OpeningHours = Record<DayOfWeek, { open: string, close: string } | null>

// A tournament/event venue — previously a read-only lookup for AddModal
// dropdowns (useLocationsQuery.ts), now also the domain type behind the
// /locations management page (2026-08-16).
export interface Location {
  id: number
  uuid: string
  name: string
  address: string
  city: string
  province: string
  postalCode: string
  country: string
  phone: string | null
  email: string | null
  website: string | null
  // Precise Google Maps place link — takes priority over the generic
  // address-search fallback (googleMapsUrl() util) when set, see
  // supabase/migrations/20260816120000_add_locations_google_maps_url.sql.
  googleMapsUrl: string | null
  openingHours: OpeningHours | null
  image: string | null
  facebook: string | null
  instagram: string | null
  telegramChannel: string | null
  whatsapp: string | null
  // Simple boolean, not a date range — no reopening date is tracked, this
  // only drives the "chiuso temporaneamente" badge/banner and disables (but
  // doesn't clear) the opening-hours editor.
  temporarilyClosed: boolean
}

// --- Campionato Cittadino -----------------------------------------------------
// Backed by mock data in server/api/cittadino.ts (no Supabase table exists yet —
// see the P1 entry in docs/BACKLOG.md), same mapping convention as Tournament.

// One event of the championship calendar: a column in the standings matrix.
export interface CittadinoEvent {
  uuid: string
  name: string
  date: string
  format: string
}

// A raw placement as it comes back from the API — one player's finishing position
// at one event, before any scoring is applied.
export interface CittadinoPlacement {
  playerUuid: string
  playerName: string
  eventUuid: string
  rank: number
}

// A single player's result at a single event: one cell of the matrix.
export interface CittadinoResult {
  eventUuid: string
  rank: number
  points: number
  // Whether this result is among the player's best CITTADINO_COUNTED_RESULTS and
  // therefore contributes to their total.
  counted: boolean
}

// One player's row in the standings matrix.
export interface CittadinoStanding {
  position: number
  playerUuid: string
  playerName: string
  total: number
  eventsPlayed: number
  // Highest single-event score — the regulation's first tie-break.
  bestSingle: number
  resultsByEvent: Record<string, CittadinoResult>
}

// --- Per-format standings (Commander/Premodern/Pauper) mock ---------------------
// Backed by mock data in server/api/commander-standings.ts, same convention as the
// Cittadino types above. Best-N truncation like Cittadino, but the N is smaller
// and per-format: Commander counts the best 4 of its 5 events (confirmed
// 2026-08-09) — see useCommanderStandingsQuery.ts.

export interface FormatStandingEvent {
  uuid: string
  name: string
  date: string
}

export interface FormatStandingPlacement {
  playerUuid: string
  playerName: string
  eventUuid: string
  rank: number
}

export interface FormatStandingResult {
  rank: number
  points: number
  // Whether this result is among the player's best-N and therefore contributes to
  // their total — the rest stay on the row marked as dropped.
  counted: boolean
  // Flat bonus for showing up, confirmed for Commander 2026-08-09. Unlike
  // `points`, it is awarded for every event played regardless of `counted` — a
  // dropped result still earned its participation point.
  participationPoints: number
}

export interface FormatStandingRow {
  position: number
  playerUuid: string
  playerName: string
  total: number
  resultsByEvent: Record<string, FormatStandingResult>
}

// --- Trash --------------------------------------------------------------
// The domains that support soft delete (deleted_at) today — mirrors
// server/utils/idRequest.ts's SoftDeletableTable union, one entry per table
// name mapped in app/utils/trash/trashEntities.ts.
export type TrashEntity
  = 'tournament' | 'league' | 'event' | 'transaction' | 'wantedCard' | 'mtgFormat' | 'location'

// One row across any soft-deleted table, merged into a single shape by
// useTrashQuery.ts — same "combine several reads into one derived list"
// convention as Event's tournamentCount join.
export interface TrashItem {
  entity: TrashEntity
  id: number
  uuid: string
  name: string
  deletedAt: string
  // '' when unknown (row soft-deleted before the deleted_by column existed,
  // migration 20260823110000) — same convention as Transaction's own
  // createdBy/updatedBy.
  deletedBy: string
  // The deleted_by column's raw uuid value (null under the same "unknown"
  // condition as deletedBy) — feeds AssociateTag's associateUuid prop for
  // the membership-status hover popover, deletedBy alone is just the label.
  deletedByUuid: string | null
}

// --- Calendar day-dot hints ----------------------------------------------
// Shared by DateRangePicker.vue's `highlightedDates` (issue #37) and
// StartDatePickerField.vue's own (issue #37 follow-up, 2026-08-23) — one
// entry per date to dot with a status-colored UChip + hover tooltip.
// `color` is the domain's own status color (e.g. tournamentStatusColor()),
// `label` is the caller's own pre-formatted hover text — both components
// stay generic across domains rather than knowing about
// Tournament/Event/League shapes themselves.
export interface CalendarHighlightedDate {
  date: Date
  color: StatusColor
  label: string
}
